### ISSUE TITLE
The extension mutes everything, not just Spotify.

### ISSUE THREAD

**Issue by str** [danigm/spotify-ad-blocker#1]
The extension mutes everything, not just Spotify.

**Comment by str** [comment]
I've just tested the update, but it's not working. Nothing gets muted now.

**Comment by danigm** [comment]
I've detected that the fallback when the spotify mixer cannot be found was wrong, so I've fixed. Maybe that solves your problem, but I think that in your case will mute all. I've tested in my system with the spotify flatpak and it works for me right now.

https://github.com/danigm/spotify-ad-blocker/commit/d0263136dcc9a623d977ed10717af190adb55b52

Can you give me the name of the spotify client in the gnome-control-center, sound panel?

**Comment by str** [comment]
![image](https://user-images.githubusercontent.com/123817/73285315-72447400-41bb-11ea-92b0-ed1763dc34e4.png)

From `ps`

```
/usr/share/spotify/spotify
/usr/share/spotify/spotify --type=zygote --no-sandbox --log-file=/usr/share/spotify/debug.log --log-severity=disable --product-version=Spotify/1.1.10.546 --lang=en-US
/usr/share/spotify/spotify --type=gpu-process --field-trial-handle=13364264929084020296,16101809713612805776,131072 --disable-features=ExtendedMouseButtons,NetworkService --no-sandbox --log-file=/usr/share/spotify/debug.log --log-severity=disable --product-version=Spotify/1.1.10.546 --lang=en-US --gpu-preferences=KAAAAAAAAAAgAAAgAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --log-file=/usr/share/spotify/debug.log --service-request-channel-token=4841130542939864281
/usr/share/spotify/spotify --type=renderer --no-sandbox --log-file=/usr/share/spotify/debug.log --field-trial-handle=13364264929084020296,16101809713612805776,131072 --disable-features=ExtendedMouseButtons,NetworkService --lang=en-US --log-file=/usr/share/spotify/debug.log --log-severity=disable --product-version=Spotify/1.1.10.546 --disable-spell-checking --num-raster-threads=4 --enable-main-frame-before-activation --service-request-channel-token=12783805158646167012 --renderer-client-id=3 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
 ```

from apt:

```
spotify-client/stable,now 1:1.1.10.546.ge08ef575-19 amd64 [installed]
```

**Comment by danigm** [comment]
it looks like in your case it's capitalized and in my case it's lowercase, I'll fix that right now.

**Comment by str** [comment]
Hi!  I tried your changeset https://github.com/danigm/spotify-ad-blocker/commit/7166017fa7e3fc4d2f9aaf63976081b0b9cc9a8e but it does not work. Nothing gets muted. 

Can we add some kind of log/debug flag so we can debug what the issue is?

**Comment by danigm** [comment]
You can try to open a terminal and run `journalctl -f` and then activate the extension and open the spotify, to check if you get there some traceback or information related to this extension.

**Comment by str** [comment]
NM, it's working now. THANK YOU!
