### ISSUE TITLE
Some ads aren't being blocked.

### ISSUE THREAD

**Issue by Blackrucat** [danigm/spotify-ad-blocker#10]
This extension it's getting less helpful every day, some ads aren't being muted, I am waking up scared, because I was listening to jazz for sleep, and then McDonald's ads came up blowing my speakers and waking me up.

**Comment by prathamVaidya** [comment]
Can you provide a screenshot of spotify when the ad isn't muted.

**Comment by Blackrucat** [comment]
It's already fixed, I don't know why.
I am not having this bug anymore.
But some videos ads are being showed

**Comment by danigm** [comment]
I've detected some ads without title, so I've added a new title to the list to block here: https://github.com/danigm/spotify-ad-blocker/commit/31748890edfbd2c9984fcf133cea5fa31a80b65b

I'm closing this. If you detect some ad not blocked, please let me know so we can add the title used by spotify to the list of blocked ads.
