### ISSUE TITLE
Auto Enable Extension on startup

### ISSUE THREAD

**Issue by prathamVaidya** [danigm/spotify-ad-blocker#11]
I need to click on the icon to enable muting ads after every bootup. It will be better if automatically do that and even there's no need for a button in the overview.

**Comment by prathamVaidya** [comment]
@danigm I want to solve all the issues. Can you tell me how do you test this thing. I mean do you wait for Spotify to play ads or something else.

**Comment by danigm** [comment]
> @danigm I want to solve all the issues. Can you tell me how do you test this thing. I mean do you wait for Spotify to play ads or something else.

Yes, that's exactly what I do, I don't have any other way to test this.

**Comment by danigm** [comment]
This is fixed now in master: https://github.com/danigm/spotify-ad-blocker/commit/ab2f44b30936e9fa3ddb94852d29b0721ed2d915
