### ISSUE TITLE
Port to GNOME 41

### ISSUE THREAD

**Issue by DiogoToraci** [danigm/spotify-ad-blocker#15]
Hello, I hope you are doing well, Fedora was release today with Gnome 41 and I would like to keeping using this wonderfull extension, I hope that is some plans for updates.

Thanks in advance

**Comment by danigm** [comment]
I've not tested yet, but it should work just increasing the version number here: https://github.com/danigm/spotify-ad-blocker/blob/master/metadata.json#L7

**Comment by DiogoToraci** [comment]
@danigm Thank you it worked.

**Comment by danigm** [comment]
Thanks for testing! I've just modified in the repository and uploaded a new version to extensions.gnome.org, so it'll be available soon for everyone.
