### ISSUE TITLE
Don't use title/artist for ad detection

### ISSUE THREAD

**Issue by XECortex** [danigm/spotify-ad-blocker#16]
You are currently comparing the title/artist to detect if the current track is an ad. However, the Spotify track *ID* already includes what type of content is playing, eg. `spotify:track:987...`, `spotify:podcast:456...` or `spotify:ad:321...`. As you can see, an ID starting with `spotify:ad` indicates that an ad is playing.

I already used this method in my own script [here](https://github.com/XECortex/spotifytools/blob/9cf1b0f15a255980376a05e300ce571c18659de8/src/util.py#L105).

**Comment by danigm** [comment]
Thanks a lot, I've updated the code and it's working correctly. It's a nice simplification and now we don't need the guessing.
