### ISSUE TITLE
Feature request: Reduce volume of ads

### ISSUE THREAD

**Issue by bmaupin** [danigm/spotify-ad-blocker#18]
@danigm I have a strange use case; instead of muting ads, I just want to reduce the volume during ads, then restore the volume when the ads are finished. I played around with the code and it's pretty straightforward.

What I would like to know, is would a pull request adding this functionality be accepted? It would look something like this:

- Change the extension to reduce the volume to 0% (effectively muting the ads, keeping the current behaviour as-is)
- Add an extension settings page so the user can change the volume reduction amount
  - This would also help with some of the work for #6 which would also require a settings page
  - In addition, a settings page would allow other values to be configured; for example, right now the 500 ms delay before unmuting doesn't seem to be long enough on my computer (https://github.com/danigm/spotify-ad-blocker/blob/master/extension.js#L95). I'd be happy to submit a PR for this as well.

If this type of pull request would be accepted, I can do the work. If not then feel free to close this issue and I can just fork this repo instead.

Thanks!

**Comment by danigm** [comment]
> is would a pull request adding this functionality be accepted?

Yes, sure, any improvement is welcome.
