### ISSUE TITLE
[Ask] Gnome Shell 3.28

### ISSUE THREAD

**Issue by smujaddid** [danigm/spotify-ad-blocker#2]
Do you have any plan to support gnome shell 3.28?

**Comment by danigm** [comment]
It's too old and I've not an installation to test, but maybe you can try, just edit this file:

https://github.com/danigm/spotify-ad-blocker/blob/master/metadata.json#L1

Add 3.28 in the shell-version array and check if it works. The plugin is really simple, it's possible that it works in that version too.

**Comment by smujaddid** [comment]
> It's too old and I've not an installation to test, but maybe you can try, just edit this file:
> 
> https://github.com/danigm/spotify-ad-blocker/blob/master/metadata.json#L1
> 
> Add 3.28 in the shell-version array and check if it works. The plugin is really simple, it's possible that it works in that version too.

Sure, I'll try this. I hope it works. Thanks!

**Comment by smujaddid** [comment]
I have tested it and looks like it is working for 3.28. Thanks.

**Comment by smujaddid** [comment]
Unfortunately, after playing for more than 1 hour, it muted all the songs instead of only the ads.
