### ISSUE TITLE
Sometimes volume isn't properly unmuted

### ISSUE THREAD

**Issue by bmaupin** [danigm/spotify-ad-blocker#25]
I've seen a few instances in which the volume isn't properly unmuted, and I suspect this is what's happening:

1. When `mute` is called, it saves the volume of the Spotify audio streams so they can be restored
2. When Spotify plays a video ad, sometimes it creates a Chromium audio stream (#17). But sometimes it creates an extra Spotify audio stream. When `unmute` is called, for each stream that originally existed it will restore the volume, but for any extra streams the volume will be set to `undefined` (in practice it seems to get set to `0`).

I have a few ideas for how to fix it:

- A: The simplest would be to just save the volume of the first stream during `mute` and then apply that across all the streams in `unmute`. This was actually what I originally implemented (a541669) but then I decided to store the volume per stream separately in case the user had configured the volume of the different streams differently (780d7da). But is it reasonable to expect users to do that? Maybe it was overkill ...
- B: Another relatively simple approach would be just to set the volume to full (65535?) when unmuting
- C: Yet another idea I had was to reverse the mute logic. So the mute logic is something like: muted volume = current volume * ad-volume-percentage / 100. So then to reverse it, when unmuting it would be: unmuted volume = current volume / (ad-volume-percentage / 100)
- D: As if that wasn't enough, I had one final idea 😅 Add a new configuration option for the volume percentage to set after unmuting, and default it to 100.

Right off the bat, I don't like idea D. I think it's a bit overengineered and would remove the user's ability to set the volume of the Spotify stream (since it would always get reset to 100%). Along those lines, I think that would eliminate idea B.
 as well.

So I guess that leaves ideas A and C.

In theory idea C would actually be the simplest I think? Because it would allow muting and unmuting without the need to save the volume before muting, so that logic could be removed. And it would allow the user to set the volume of the different streams independently.

I think I'll go ahead and test out idea C but @danigm let me know if you have a different preference.

**Comment by danigm** [comment]
I think that I don't understand very well the option C, in any case, I like the option A, is simple and I don't think that a different volume for different streams is something that anyone uses. But if you make it work for all the cases with the option C, go ahead, and let's see if it works as expected

**Comment by bmaupin** [comment]
> I think that I don't understand very well the option C

I probably didn't explain it very well :)

Basically right now to mute, it's current volume * mute volume percentage.

So option C would be to do the opposite: current volume / mute volume percentage.

Here's the diff:

```diff
diff --git a/extension.js b/extension.js
index 9dbd15c..68881f3 100644
--- a/extension.js
+++ b/extension.js
@@ -41,8 +41,6 @@ var AdBlocker = class AdBlocker {
         this.muteTimeout = 0;
         this.enable();
 
-        this.volumeBeforeAds = [];
-
         this.settings.connect('changed::show-indicator', () => {
             if (this.settings.get_boolean('show-indicator')) {
                 Main.panel._rightBox.insert_child_at_index(this.button, 0);
@@ -95,7 +93,6 @@ var AdBlocker = class AdBlocker {
         }
 
         for (const stream of this.streams) {
-            this.volumeBeforeAds.push(stream.get_volume());
             stream.set_volume(stream.get_volume() * this.settings.get_int('ad-volume-percentage') / 100);
             // This needs to be called after changing the volume for it to take effect
             stream.push_volume();
@@ -120,7 +117,7 @@ var AdBlocker = class AdBlocker {
         this.muteTimeout = 0;
 
         for (const stream of this.streams) {
-            stream.set_volume(this.volumeBeforeAds.shift());
+            stream.set_volume(stream.get_volume() / (this.settings.get_int('ad-volume-percentage') / 100));
             stream.push_volume();
         }
```

I'll test it out for a while and see how well it works.

But if you still prefer option A I can do that instead. Either one is pretty simple I think.

**Comment by bmaupin** [comment]
I see a problem with this code already :man_facepalming: It will cause a division by zero if ad-volume-percentage is 0.

Of course we could add logic to account for that, but maybe it just means that your instinct was right and we should just stick with option A :)

I think I'll go ahead an implement option A and test it out for a bit.
