### ISSUE TITLE
Spotify doesn't properly unmute when extension is closed

### ISSUE THREAD

**Issue by bmaupin** [danigm/spotify-ad-blocker#27]
I've found a bug caused by #24 (unrelated to #26 so that one should be safe to merge :sweat_smile: )

#### To reproduce

1. Close Spotify while an ad is playing
2. Disable and re-enable the extension (I've been using the Gnome extension manager for this)
3. Observe that the system volume has been increased, possibly to full volume
1. Start Spotify and press play
2. Observe that the Spotify stream volume will remain reduced/muted

I think this scenario could occur during normal usage if the user closes Spotify while playing an ad, then logs out/shuts down/reboots, because `disable()` is called whenever the user logs out of Gnome. Or even when the screen is locked apparently, as per https://gjs.guide/extensions/overview/anatomy.html#extension-js-required

#### The cause

Because of #24, `unmute()` will be called from `disable()`. Unfortunately, the Spotify stream seems to have already been closed at that point. `get streams()` returns the default sink as a fallback, so the unmute logic gets applied to the system volume instead of the Spotify stream.

#### The fix

This was a lot harder than I expected. After trying a bunch of approaches, I have two remaining ideas:

* A: Ultimately, I think the pre-mute volume needs to be stored in a persistent way. My idea is to store it in GSettings, but not expose it in the Settings UI. This should basically allow the extension to work as should be expected without requiring any additional input from the user.
* B: The simpler approach would be to not store the volume before muting, and just set the volume to 100% when unmuting. But I don't think this gives the best user experience. Gnome does seem to preserve the previous stream volume when creating a new stream I could see users relying on this and setting the volume of the Spotify stream specifically.

I'll try to work on a PR for idea A and test it out.

**Comment by bmaupin** [comment]
Hmm, I just re-read the description for #24 and it was supposed to fix this exact scenario. So I'll try to do some more thorough testing this time.

**Comment by danigm** [comment]
Great investigation :smiley:, I think that option A is a good option. I can think about other scenarios where the stream is not there when we try to unmute and could lead to low volume, like for example if we close the spotify app during an ad. So maybe storing the volume in a setting could solve this kind of problems, to unmute correctly when detected.

**Comment by bmaupin** [comment]
I'm wondering if I did this when I tested #24:

1. Wait until an ad is playing
2. Pause Spotify (this is just to make sure the ad doesn't finish playing before the testing is done)
3. Using the Gnome extension manager, disable and then re-enable the plugin
4. Then resume playing

The problem with this, of course, is that Spotify is running the whole time, and so it would only cover scenarios where the user shuts down/reboots/logs out and the Spotify audio stream is still open when the extension's `disable` method is called.

The proper test scenario, however, involves closing Spotify while the ad is playing, then disabling/enabling the extension (as detailed above).

Still testing ...

**Comment by bmaupin** [comment]
I'm still testing ...

I ran into one issue, in which everything else seemed to be working but it seems the Spotify stream wasn't available, in which case the unmute/mute logic got applied to the default system audio sink. @danigm if it's okay with you, I think I'll remove the logic that returns the default sink in `get streams`; I can see why it might be nice to just mute/unmute the default sink if the spotify stream doesn't exist, the problem is there are enough corner cases where the spotify stream has just been closed (or not opened yet) and then the mute logic gets applied to the spotify stream but the unmute logic gets applied to the default sink (or vice-versa). It seems better to just remove that fallback.

Then I ran into another problem: I'm persisting volumeBeforeAds in `disable()` but I noticed today that `disable` wasn't called last time I shut down my PC :man_facepalming: Going back through old logs this appears to be consistent. Here's the only documentation I've found:

>     * This function is called when your extension is uninstalled, disabled in
>     * GNOME Extensions, when you log out or when the screen locks.

(https://gjs.guide/extensions/overview/anatomy.html#extension-js-required)

This seems like a Gnome bug, but on the other hand it doesn't say anything about shutting down. At any rate, I don't think I can put the logic in `disable`

I could persist volumeBeforeAds to gsettings every time it changes, but that seems like a lot of unnecessary disk writes. My current thinking is to go back to something I was working on before, where I tried to listen for the close event on the spotify stream and unmute the stream then. That didn't work, but I think I could potentially use that same logic to persist volumeBeforeAds. I'll just have to make sure that gets called when shutting down ...

**Comment by danigm** [comment]
> I think I'll remove the logic that returns the default sink in `get streams`

Sounds good to me, as far as I can remember, the default stream is there because at the beginning  I was just muting the default sink, and when I change to use the `spotify` sink I just make it fallback to the default in case that spotify is not there, but I think it's okay to do not mute the default sink in any case. Just make sure that if the sink can't be found, the extension doesn't crash.

**Comment by bmaupin** [comment]
> but I noticed today that disable wasn't called last time I shut down my PC

It seems like this is a bug after all: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2621

Next I tried subscribing to the spotify audio stream close signal, but that wasn't called either when I shut down my PC.

I found a possible workaround here so I'll try that next: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5721#note_1523101

**Comment by bmaupin** [comment]
> I found a possible workaround here so I'll try that next: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5721#note_1523101

... so I was looking at the workaround and I think I'm overcomplicating things.

It feels like the simplest solution would be to read/write volumeBeforeAds directly from GSettings every time. Then we don't have to worry about storing it/restoring it, etc. I was worried about unnecessary disk writes but we're talking about writing one value, what, a few times an hour? That doesn't seem unreasonable to me at all. I have a feeling my web browser is probably making more writes to disk than that (for caching or whatever it may be) as I type this comment.

I'll make the changes and thoroughly test it before submitting a PR.
