### ISSUE TITLE
problem with ads

### ISSUE THREAD

**Issue by vitw** [danigm/spotify-ad-blocker#5]
At the end of an ad I hear 1 second of it.Please suggest how to fix it or fix it.

**Comment by danigm** [comment]
Yes, I noticed this too. Maybe we can add a delay or fade-in effect to avoid this problem.

**Comment by prathamVaidya** [comment]
Are you sure 1 sec delay is enough? I think delay should be something between 500ms - 800ms

**Comment by danigm** [comment]
> Are you sure 1 sec delay is enough? I think delay should be something between 500ms - 800ms

I don't know exactly, the time will depend on how the spotify app changes the title and the sound, sometimes the title changes before the ad ends, so maybe something like that will work.
