### ISSUE TITLE
Problems with AD 

### ISSUE THREAD

**Issue by Blackrucat** [danigm/spotify-ad-blocker#7]
Sometimes Spotify gets stucked in the AD even if I try to click in another music or play other music. 
To bring Spotify back to normal I have to close and open it again.

**Comment by prathamVaidya** [comment]
@Blackrucat  Are you sure its because of the extension because I think spotify-linux has this problem and it stuck randomly.

**Comment by emanuele-leopardi** [comment]
I'm getting the same behaviour but I'm using spotify from the browser rather than from the client itself

**Comment by bmaupin** [comment]
Yeah I think this isn't related to this extension. Even before I started using the extension, Spotify ads would get stuck sometimes. There's nothing in this extension that would cause an ad to get stuck. It's only modifying the volume.

@danigm I would recommend closing this issue.
