### ISSUE TITLE
Port to GNOME 40

### ISSUE THREAD

**Issue by amitanilkulkarni** [danigm/spotify-ad-blocker#9]
The extension works great, but it's incompatible with GNOME 40.
Would love it if it gets ported. Thanks!

**Comment by prathamVaidya** [comment]
@amitanilkulkarni  Hey can you check if this extension works on Gnome 40 from this link and give the feedback
https://github.com/prathamVaidya/spotify-ad-blocker.git

**Comment by Ruados** [comment]
@prathamVaidya came here for the same now that I've upgraded to F34. This one works fine on Gnome 40.

**Comment by danigm** [comment]
I've just uploaded the new version to extensions.gnome.org, so it's now available for gnome 40.
